In [1]:
# check sample_mimic.db to make sure the data is populated
import sqlite3
import pandas as pd

# Path to your SQLite file
db_path = 'mimic_sparql/mimicsql/evaluation/mimic_db/mimic.db'

# Connect to the database
conn = sqlite3.connect(db_path)
cursor = conn.cursor()

# Get list of all tables
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = [row[0] for row in cursor.fetchall()]
print(f"Found {len(tables)} tables:\n", tables)

# Check each table
empty_tables = []
for table in tables:
    try:
        # Count rows
        cursor.execute(f"SELECT COUNT(*) FROM {table};")
        row_count = cursor.fetchone()[0]
        print(f"Table: {table} - Rows: {row_count}")
        
        if row_count == 0:
            empty_tables.append(table)
        else:
            # Optional: Show first 5 rows
            df = pd.read_sql_query(f"SELECT * FROM {table} LIMIT 5;", conn)
            print(df.head())
            print('-' * 60)
    except Exception as e:
        print(f"Error reading table {table}: {e}")
        continue

# Summary
if empty_tables:
    print("\n⚠️ Empty tables found:", empty_tables)
else:
    print("\n✅ All tables contain data.")

# Clean up
cursor.close()
conn.close()

Found 5 tables:
 ['DEMOGRAPHIC', 'DIAGNOSES', 'PROCEDURES', 'PRESCRIPTIONS', 'LAB']
Table: DEMOGRAPHIC - Rows: 100
   SUBJECT_ID  HADM_ID              NAME MARITAL_STATUS  AGE  \
0        1121   181293       Jeff Jarvis           None   89
1       25543   124588      Michael Witt           None    0
2       94762   160707     Walter Locher        MARRIED   67
3       55094   135633  Lawrence Wibbens        MARRIED   56
4       76446   104538      Jason Walker        WIDOWED   86

                   DOB GENDER LANGUAGE           RELIGION ADMISSION_TYPE  ...  \
0  1887-11-09 00:00:00      M     None              OTHER         URGENT  ...
1  2180-11-30 00:00:00      M     None       UNOBTAINABLE        NEWBORN  ...
2  2098-04-23 00:00:00      M     ENGL  PROTESTANT QUAKER       ELECTIVE  ...
3  2126-10-22 00:00:00      M     ENGL           CATHOLIC      EMERGENCY  ...
4  2058-12-29 00:00:00      M     ENGL  PROTESTANT QUAKER       ELECTIVE  ...

   EXPIRE_FLAG         ADMISSION_LOCATION         DISCHARGE_LOCATION  \
0            0  PHYS REFERRAL/NORMAL DELI  DISC-TRAN CANCER/CHLDRN H
1            0  PHYS REFERRAL/NORMAL DELI                       HOME
2            1  PHYS REFERRAL/NORMAL DELI               DEAD/EXPIRED
3            0  CLINIC REFERRAL/PREMATURE           HOME HEALTH CARE
4            0  PHYS REFERRAL/NORMAL DELI           HOME HEALTH CARE

                                           DIAGNOSIS                  DOD  \
0                            CORONARY ARTERY DISEASE                 None
1                                            NEWBORN                 None
2  NEOPLASM OF UNCERTAIN BEHAVIOR OF OTHER LYMPHA...  2165-06-24 00:00:00
3                                  ABDOMINAL ABSCESS                 None
4            SQUAMOUS CELL CARCINOMA ORAL TONGUE/SDA                 None

  DOB_YEAR DOD_YEAR            ADMITTIME            DISCHTIME  ADMITYEAR
0     1887      NaN  2187-11-09 15:44:00  2187-11-16 11:25:00       2187
1     2180      NaN  2180-11-30 19:25:00  2180-12-04 10:57:00       2180
2     2098   2165.0  2165-06-03 11:25:00  2165-06-24 03:23:00       2165
3     2126      NaN  2182-02-08 22:31:00  2182-03-04 14:28:00       2182
4     2058      NaN  2144-12-07 07:15:00  2144-12-14 17:00:00       2144

[5 rows x 23 columns]
------------------------------------------------------------
Table: DIAGNOSES - Rows: 1099
   SUBJECT_ID  HADM_ID ICD9_CODE               SHORT_TITLE  \
0        1121   181293      2859                Anemia NOS
1        1121   181293      3970   Tricuspid valve disease
2        1121   181293     78551         Cardiogenic shock
3        1121   181293      3963  Mitral/aortic val insuff
4        1121   181293     39891   Rheumatic heart failure

                                          LONG_TITLE
0                                Anemia, unspecified
1                        Diseases of tricuspid valve
2                                  Cardiogenic shock
3  Mitral valve insufficiency and aortic valve in...
4               Rheumatic heart failure (congestive)
------------------------------------------------------------
Table: PROCEDURES - Rows: 383
   SUBJECT_ID  HADM_ID  ICD9_CODE               SHORT_TITLE  \
0        1121   181293       3523  Opn/oth rep mtrl vlv-tis
1        1121   181293       8968    Oth cardiac mon output
2        1121   181293       3964   Intraop cardiac pacemak
3        1121   181293       3961   Extracorporeal circulat
4       25543   124588       9955           Vaccination NEC

                                          LONG_TITLE
0  Open and other replacement of mitral valve wit...
1    Monitoring of cardiac output by other technique
2                   Intraoperative cardiac pacemaker
3  Extracorporeal circulation auxiliary to open h...
4  Prophylactic administration of vaccine against...
------------------------------------------------------------
Table: PRESCRIPTIONS - Rows: 6622
   SUBJECT_ID  HADM_ID ICUSTAY_ID DRUG_TYPE                         DRUG  \
0       94762   160707       None      MAIN                     Glucagon
1       94762   160707       None      MAIN                 Dextrose 50%
2       94762   160707       None      MAIN  Heparin Flush (10 units/ml)
3       94762   160707       None      BASE                          Bag
4       94762   160707       None      BASE                          Bag

  FORMULARY_DRUG_CD ROUTE DRUG_DOSE
0            GLUC1I    IM       1mg
1           DEX50SY    IV    12.5gm
2         HEPA10SYR    IV       1mL
3             BAG50    IV      50mL
4             BAG50    IV     100mL
------------------------------------------------------------
Table: LAB - Rows: 27706
   SUBJECT_ID  HADM_ID  ITEMID            CHARTTIME  FLAG VALUE_UNIT  \
0        1121   181293   50802  2187-11-09 15:42:00  None     0mEq/L
1        1121   181293   50804  2187-11-09 15:42:00  None    25MEQ/L
2        1121   181293   50818  2187-11-09 15:42:00  None    35MM HG
3        1121   181293   50820  2187-11-09 15:42:00  None  7.44UNITS
4        1121   181293   50821  2187-11-09 15:42:00  None    68MM HG

                  LABEL  FLUID   CATEGORY
0           Base Excess  Blood  Blood Gas
1  Calculated Total CO2  Blood  Blood Gas
2                  pCO2  Blood  Blood Gas
3                    pH  Blood  Blood Gas
4                   pO2  Blood  Blood Gas
------------------------------------------------------------

✅ All tables contain data.

In [ ]:
# create